# Interpret make's command line arguments as go or go run arguments.
# See this for more details:
#   https://stackoverflow.com/a/14061796
ifeq (go,$(firstword $(MAKECMDGOALS)))
  RUN_ARGS := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
  $(eval $(RUN_ARGS):;@:)
endif

ifeq (gorun,$(firstword $(MAKECMDGOALS)))
  RUN_ARGS := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
  $(eval $(RUN_ARGS):;@:)
endif

.PHONY: default
default: .docker-setup

.PHONY: .go
go: .docker-setup
	docker run --rm -v `pwd`:/workspace goalgo-goimage sh -c cd /workspace && go $(RUN_ARGS)

.PHONY: .gorun
gorun: .docker-setup
	docker run --rm -v `pwd`:/workspace goalgo-goimage sh -c cd /workspace && go run ./$(RUN_ARGS)

.docker-setup:
	docker build . -t goalgo-goimage
	echo "This file was generated by 'make' during '.docker-setup' Makefile target." > .docker-setup
	echo "It prevents 'make' to attempt '.docker-setup' target again after it's done." >> .docker-setup

.PHONY: .docker-cleanup
.docker-cleanup:
	docker image rm goalgo-goimage
	rm .docker-setup
